"use client";

import { DocPage } from "@/components/DocPage";
import { FlaskConical, Code, ShieldCheck, Zap } from "lucide-react";

export default function UnitTestGenPage() {
  return (
    <DocPage
      breadcrumb="Pre-Merge_Automation / Unit_Test_Gen"
      badge="TEST GENERATOR"
      badgeColor="#F97316"
      title="AUTOMATED UNIT TEST GENERATION"
      subtitle="Generate missing unit tests for code modifications automatically."
      description={`Writing unit tests can be tedious. GitRabbit analyzes code changes in your pull requests and automatically generates unit tests for new logic paths, edge cases, and error handlers. Tests are designed to match your existing framework (Jest, Vitest, Pytest, Go testing) and testing styles.`}
      features={[
        { icon: Code, title: "Framework Auto-Detection", desc: "Identifies whether your codebase utilizes Jest, Pytest, Vitest, Go, or JUnit, and formats code accordingly." },
        { icon: ShieldCheck, title: "Edge Case Identification", desc: "Specifically targets boundary conditions (empty lists, null limits, overflow parameters)." },
        { icon: Zap, title: "One-Click Append", desc: "Adds tests directly to your test suite files with one click." },
      ]}
      steps={[
        { step: "Step 01", title: "Analyze Code Changes", desc: "GitRabbit looks at new functions or logic paths introduced in the PR." },
        { step: "Step 02", title: "Draft Test Suites", desc: "The agent writes matching test cases based on mock input states." },
        { step: "Step 03", title: "Submit Test File", desc: "Suggestions are posted in the PR comment section, or appended to files (like 'math.test.ts')." },
      ]}
      codeExample={{
        label: "Auto-generated test using Vitest / Jest",
        code: `// Auto-generated by GitRabbit for calculateTax()
import { describe, it, expect } from 'vitest';
import { calculateTax } from './tax-service';

describe('calculateTax() edge cases', () => {
  it('should return 0 when income is negative', () => {
    expect(calculateTax(-500)).toBe(0);
  });

  it('should apply maximum bracket for high incomes', () => {
    expect(calculateTax(500000)).toBe(175000);
  });
});`,
      }}
      proTips={[
        "Configure standard Mock files in '.gitrabbit.yml' to help the agent mock database or API queries correctly.",
        "Combine Test Generation with One-Click Fixes to keep test suites matching code refactors instantly.",
      ]}
      prevPage={{ href: "/docs/plan", label: "CodeRabbit Plan" }}
      nextPage={{ href: "/docs/docstrings", label: "Docstring Generation" }}
    />
  );
}
