"use client";

import { DocPage } from "@/components/DocPage";
import { Bug, AlertTriangle, ShieldCheck, HelpCircle } from "lucide-react";

export default function BugDetectionPage() {
  return (
    <DocPage
      breadcrumb="PR_Reviews / Bug_Detection"
      badge="CORE DEFECTS"
      badgeColor="#EF4444"
      title="BUG & DEFECT DETECTION"
      subtitle="Identify runtime faults, logic errors, race conditions and AI slop."
      description={`GitRabbit scans your PR changes for hidden runtime bugs that static code linters can't catch. By compiling an internal, context-aware syntax graph, GitRabbit spots resource leaks, concurrency deadlocks, missing error boundaries, and typical AI-generated code bloat (hallucinated parameters).`}
      features={[
        { icon: AlertTriangle, title: "Concurrency & Race Checks", desc: "Find missing mutexes, unhandled goroutines, and overlapping thread locks." },
        { icon: ShieldCheck, title: "Null Pointer Detection", desc: "Expose locations where lack of optional chaining or type guards will crash the frontend." },
        { icon: HelpCircle, title: "AI Slop Filtering", desc: "Identifies unnecessary boilerplate or hallucinated API parameters common in code generated by other LLM agents." },
      ]}
      steps={[
        { step: "Analyze Diff", title: "Diff Parsing", desc: "The diff is scanned, and related methods across imported files are analyzed for side effects." },
        { step: "Evaluate Logic", title: "State Machine Review", desc: "Checks how your state transitions impact data integrity or database transactions." },
        { step: "Post Alerts", title: "Inline Flags", desc: "High-priority bugs are posted directly on the PR with red warning banners." },
      ]}
      codeExample={{
        label: "AI Slop detection flag example",
        code: `// ❌ AI Slop Detected:
// The API method call 'client.fetchUserLogs(userId, { includeDeleted: true, filterNulls: false })'
// utilizes parameters that do not exist on the current version of the logging library.
// Did you mean: 'client.fetchLogs(userId)'?`,
      }}
      proTips={[
        "Set 'severity_threshold: medium' in your config file to only get alerts for logic and security defects.",
        "Use GitRabbit's custom YAML template files to specify proprietary runtime exceptions unique to your framework.",
      ]}
      prevPage={{ href: "/docs/fixes", label: "One-Click Fixes" }}
      nextPage={{ href: "/docs/agentic-chat", label: "Agentic Chat" }}
    />
  );
}
